---
abstract: 'XML::IODEF::Simple plugin for converting from TLP'
author:
  - 'Wes Young, <wes@barely3am.com>'
build_requires:
  ExtUtils::MakeMaker: 6.42
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 1.00'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: XML-IODEF-Simple-Plugin-TLP
no_index:
  directory:
    - inc
    - t
requires:
  XML::IODEF::Simple: 0.00
resources:
  license: http://dev.perl.org/licenses/
version: 0.00_02
